 [general]
resolution = [768, 768]
batch_size = 1
caption_extension = ".txt"
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
image_directory = "/home/en1u2/AI-Stuff/References/regular"
num_repeats = 1

[[datasets]]
image_directory = "/home/en1u2/AI-Stuff/References/water"
num_repeats = 1

[[datasets]]
image_directory = "/home/en1u2/AI-Stuff/References/dark"
num_repeats = 1

[[datasets]]
image_directory = "/home/en1u2/AI-Stuff/References/sketch"
num_repeats = 1

[[datasets]]
image_directory = "/home/en1u2/AI-Stuff/References/anime_new"
num_repeats = 1

#[[datasets]]
#image_directory = "/home/en1u2/AI-Stuff/kohya_ss/outputs/reg/woman"
#num_repeats = 1
#is_reg = true
